# Generated by Django 5.0 on 2023-12-08 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('user_position', models.CharField(max_length=255, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 12, 8, 5, 25, 56, 270047, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
