# Generated by Django 5.0 on 2023-12-08 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 5, 28, 51, 189996, tzinfo=datetime.timezone.utc)),
        ),
    ]
