# Generated by Django 5.0 on 2023-12-08 06:31

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 8, 6, 31, 29, 714331, tzinfo=datetime.timezone.utc)),
        ),
    ]
