# Generated by Django 5.0 on 2023-12-09 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 12, 9, 8, 12, 26, 609025, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 9, 8, 12, 26, 609025, tzinfo=datetime.timezone.utc)),
        ),
    ]
